# Generated by Django 5.1.6 on 2025-03-20 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('mand', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matkhau', models.CharField(max_length=255)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('loainguoidung', models.CharField(choices=[('KhachHang', 'Khách Hàng'), ('QuanTriVien', 'Quản Trị Viên')], default='KhachHang', max_length=20)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nguoidung',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('masp', models.AutoField(primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=255)),
                ('mota', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soluongtonkho', models.IntegerField(default=0)),
                ('hinhanh', models.CharField(blank=True, max_length=255, null=True)),
                ('danhmuc', models.CharField(blank=True, max_length=100, null=True)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sanpham',
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('magh', models.AutoField(primary_key=True, serialize=False)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
            ],
            options={
                'db_table': 'giohang',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('madh', models.AutoField(primary_key=True, serialize=False)),
                ('ngaydathang', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trangthai', models.CharField(choices=[('ChoXacNhan', 'Chờ Xác Nhận'), ('DangGiao', 'Đang Giao'), ('HoanThanh', 'Hoàn Thành'), ('DaHuy', 'Đã Hủy')], default='ChoXacNhan', max_length=20)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
            ],
            options={
                'db_table': 'donhang',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('madg', models.AutoField(primary_key=True, serialize=False)),
                ('sosao', models.IntegerField()),
                ('binhluan', models.TextField(blank=True, null=True)),
                ('ngaydanhgia', models.DateTimeField(auto_now_add=True)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nguoidung')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
            options={
                'db_table': 'danhgia',
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('matt', models.AutoField(primary_key=True, serialize=False)),
                ('sotien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phuongthucthanhtoan', models.CharField(choices=[('TienMat', 'Tiền Mặt'), ('ChuyenKhoan', 'Chuyển Khoản'), ('TheTinDung', 'Thẻ Tín Dụng')], max_length=20)),
                ('trangthaithanhtoan', models.CharField(choices=[('ChuaThanhToan', 'Chưa Thanh Toán'), ('DaThanhToan', 'Đã Thanh Toán')], default='ChuaThanhToan', max_length=20)),
                ('ngaythanhtoan', models.DateTimeField(blank=True, null=True)),
                ('donhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.donhang')),
            ],
            options={
                'db_table': 'thanhtoan',
            },
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField()),
                ('giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.giohang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
            options={
                'db_table': 'chitietgiohang',
                'unique_together': {('giohang', 'sanpham')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.donhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
            options={
                'db_table': 'chitietdonhang',
                'unique_together': {('donhang', 'sanpham')},
            },
        ),
    ]
