# Generated by Django 5.1.6 on 2025-03-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('MaND', models.AutoField(primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Matkhau', models.CharField(max_length=255)),
                ('SDT', models.CharField(blank=True, max_length=15, null=True)),
                ('Loainguoidung', models.CharField(choices=[('KhachHang', 'Khách Hàng'), ('QuanTriVien', 'Quản Trị Viên')], default='KhachHang', max_length=20)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
